# Generated by Django 5.2.17 on 2026-09-09 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=12, verbose_name='Status')),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fundo de caixa')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Vendas')),
                ('canceled_count', models.PositiveIntegerField(default=0, verbose_name='Canceladas')),
                ('sales_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total das vendas')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dinheiro esperado')),
                ('expected_pix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PIX esperado')),
                ('expected_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Débito esperado')),
                ('expected_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Crédito esperado')),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Dinheiro conferido')),
                ('counted_pix', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='PIX conferido')),
                ('counted_debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Débito conferido')),
                ('counted_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Crédito conferido')),
                ('difference_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença dinheiro')),
                ('difference_pix', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença PIX')),
                ('difference_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença débito')),
                ('difference_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença crédito')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Observação')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashsession', verbose_name='Caixa'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('operator',), name='unique_open_cash_session_per_operator'),
        ),
    ]
